'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "./context/AppContext";
import Navbar from "./components/Navbar";
import { usePathname } from "next/navigation";
import Footer from "./components/HomePage/Footer";
import { ToastContainer, toast } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "GreenCart",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
          {/* Show Navbar on all pages EXCEPT /login */}
          {pathname !== "/login" && !pathname.startsWith("/seller") && pathname !== "/signup" && <Navbar />}

          {children}
          {pathname !== "/login" && !pathname.startsWith("/seller") && pathname !== "/signup" && <Footer />}

          <ToastContainer />
        </AppContextProvider>
      </body>
    </html>
  );
}
