'use client'
import SellerSidebar from "@/app/components/Seller/SellerSidebar";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import SellerNavbar from "@/app/(pages)/seller/SellerNavbar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//   title: "GreenCart",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const pathname = usePathname();

    return (
        <html lang="en" className="">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased !h-[100vh] !overflow-hidden`}
            >
                {pathname !== "/seller/login" && <SellerNavbar />}
                <div className="flex h-screen">
                    {pathname !== "/seller/login" && <div >

                        < SellerSidebar />
                    </div>}

                    <div className="overflow-y-auto w-full hide-scrollbar pb-20">

                        {children}
                    </div>
                </div>

            </body>
        </html>
    );
}
